version: '2.1'

networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    ports:
      - "9431:9431"

  server2:
    build: .
    networks:
      - servers
    ports:
      - "9432:9432"

  server3:
    build: .
    networks:
      - servers
    ports:
      - "9433:9433"
